name: Build and Publish Flatpaks

on:
  workflow_dispatch:
  schedule:
    - cron: "37 3 * * *"

permissions:
  contents: write
  actions: write
  pages: write
  id-token: write

jobs:
  publish:
    uses: n-a-m-e/flatpak-build-template/.github/workflows/publish.yml@main
    with:
      app-id: |
        com.moderncsv.ModernCSV
        com.moderncsv.ModernCSV.Legacy
      source-git: https://github.com/n-a-m-e/flatpak-app-moderncsv.git
      rebuild-trigger: git moderncsv https://github.com/n-a-m-e/flatpak-app-moderncsv.git main
